title: 'PHP School - Open Source Learning for PHP'

description: >
    Learn PHP the right way... the open source way. PHP School Open Source Learning for PHP

links:
  github: 'https://github.com/php-school/learn-you-php'
  twitter: 'https://twitter.com/PHPSchoolTeam'
  slack: 'https://phpschool.herokuapp.com'
