version: '2'

services:
  php:
    volumes:
      - /var/www/html/current:/var/www/html
    working_dir: /var/www/html

  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf