version: '2'

services:
  nginx:
    ports:
      - 80
      - 443
    volumes:
      - ./etc/letsencrypt/live/phpschool.io:/etc/letsencrypt/live/phpschool.io
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html