version: '2'

services:
  php:
    container_name: php-school-fpm
    build:
      context: .
      dockerfile: .docker/files/php-school-fpm/Dockerfile
    image: php-school-fpm:latest
    environment:
      - SEND_GRID_API_KEY
      - MYSQL_USER
      - MYSQL_PASSWORD
      - XDEBUG_ENABLE
      - XDEBUG_CONFIG

    restart: always
    depends_on:
      - "db"

  db:
    container_name: php-school-db
    image: mysql:latest
    volumes:
        - "./.docker/mysql:/var/lib/mysql"
        - "./.docker/db/:/docker-entrypoint-initdb.d/"
    ports:
        - "3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

  nginx:
    container_name: php-school-nginx
    image: nginx:latest
    links:
      - php
    ports:
      - 8000:80
    volumes:
      - ./nginx-dev.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - php:ro

  redis:
      container_name: php-school-redis
      image: redis
      ports:
          - "6379"
