version: '2'

services:
  php:
    volumes:
      - .:/var/www/html
      - ../shared/workshops.json:/var/www/html/public/workshops.json

  nginx:
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
      - ../shared/workshops.json:/var/www/html/public/workshops.json
